export default {
    BLACK: 'Epilogue-Black',
    BLACK_ITALIC: 'Epilogue-BlackItalic',
    BOLD: 'Epilogue-Bold',
    BOLD_ITALIC: 'Epilogue-BoldItalic',
    EXTRA_BOLD: 'Epilogue-ExtraBold',
    EXTRA_BOLD_ITALIC: 'Epilogue-ExtraBoldItalic',
    EXTRA_LIGHT: 'Epilogue-ExtraLight',
    EXTRA_LIGHT_ITALIC: 'Epilogue-ExtraLightItalic',
    ITALIC: 'Epilogue-Italic',
    LIGHT: 'Epilogue-Light',
    LIGHT_ITALIC: 'Epilogue-LightItalic',
    MEDIUM: 'Epilogue-Medium',
    MEDIUM_ITALIC: 'Epilogue-MediumItalic',
    REGULAR: 'Epilogue-Regular',
    SEMI_BOLD: 'Epilogue-SemiBold',
    SEMI_BOLD_ITALIC: 'Epilogue-SemiBoldItalic',
    THIN: 'Epilogue-Thin',
    THIN_ITALIC: 'Epilogue-ThinItalic',
  };
