import Dimensions from './Dimensions';

export default {
  TABBAR_BOTTOM_ICON_PADDING: 3 * Dimensions.RESPONSIVE_WIDTH,
  TABBAR_CORNER_HEIGHT: 20,

  SUB_MARGIN: -9 * Dimensions.RESPONSIVE_WIDTH,
  MAIN_MARGIN: 24 * Dimensions.RESPONSIVE_WIDTH,
  EXTRA_SMALL:10 * Dimensions.RESPONSIVE_WIDTH,
  SMALL: 25 * Dimensions.RESPONSIVE_WIDTH,
  LARGE: 34 * Dimensions.RESPONSIVE_WIDTH,
  MEDIUM: 26 * Dimensions.RESPONSIVE_WIDTH,
  EXTRA_LARGE: 48 * Dimensions.RESPONSIVE_WIDTH,
};
